---
title: "Final Quiz Practical Machine Learning"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(AppliedPredictiveModeling)
library(ggplot2)
library(lattice)
library(caret)
library(e1071)
library(rattle)
library(Hmisc)
library(gbm)
library(elasticnet)
library(e1071)

#Setting working directory
setwd("~/Documents/RProjects/PracticalMachineLearning/FinalQuiz/")

#Read the data

training <- read.csv(file = "pml-training.csv" , header = TRUE)
testing <- read.csv(file = "pml-testing.csv", header = TRUE)

#Calculating the number of observations from the imported files
dim(training)
dim(testing)

#Setting seed
set.seed(1332)

#Diving our training data into two parts: Train 80%, Test 20%
Intrain <- createDataPartition(y=training$classe, p=0.8, list=FALSE)

Train <- training[Intrain,]
Test <- training[-Intrain,]

dim(Train)
dim(Test)

#Finding out variables with non-zero variance
NonZero <- nearZeroVar(Train, saveMetrics=TRUE)

NonZeroVars <- NonZero[NonZero$nzv=="TRUE",]

NonZeroVars <- names(Train) %in% c("new_window", "kurtosis_roll_belt", "kurtosis_picth_belt",
                                      "kurtosis_yaw_belt", "skewness_roll_belt", "skewness_roll_belt.1", "skewness_yaw_belt",
                                      "max_yaw_belt", "min_yaw_belt", "amplitude_yaw_belt", "avg_roll_arm", "stddev_roll_arm",
                                      "var_roll_arm", "avg_pitch_arm", "stddev_pitch_arm", "var_pitch_arm", "avg_yaw_arm",
                                      "stddev_yaw_arm", "var_yaw_arm", "kurtosis_roll_arm", "kurtosis_picth_arm",
                                      "kurtosis_yaw_arm", "skewness_roll_arm", "skewness_pitch_arm", "skewness_yaw_arm",
                                      "max_roll_arm", "min_roll_arm", "min_pitch_arm", "amplitude_roll_arm", "amplitude_pitch_arm",
                                      "kurtosis_roll_dumbbell", "kurtosis_picth_dumbbell", "kurtosis_yaw_dumbbell", "skewness_roll_dumbbell",
                                      "skewness_pitch_dumbbell", "skewness_yaw_dumbbell", "max_yaw_dumbbell", "min_yaw_dumbbell",
                                      "amplitude_yaw_dumbbell", "kurtosis_roll_forearm", "kurtosis_picth_forearm", "kurtosis_yaw_forearm",
                                      "skewness_roll_forearm", "skewness_pitch_forearm", "skewness_yaw_forearm", "max_roll_forearm",
                                      "max_yaw_forearm", "min_roll_forearm", "min_yaw_forearm", "amplitude_roll_forearm",
                                      "amplitude_yaw_forearm", "avg_roll_forearm", "stddev_roll_forearm", "var_roll_forearm",
                                      "avg_pitch_forearm", "stddev_pitch_forearm", "var_pitch_forearm", "avg_yaw_forearm",
                                      "stddev_yaw_forearm", "var_yaw_forearm")
Train_V1 <- Train[!NonZeroVars]

dim(Train_V1)

#Removing variable X
Train_V2 <- Train_V1[,c(-1)]

#Describing rest of the variables 

describe(Train_V2)

#Variables with high missing values
MissingVal <- names(Train_V2) %in% c("var_accel_forearm","amplitude_pitch_forearm", "min_pitch_forearm", "max_picth_forearm",
                                    "var_yaw_dumbbell","stddev_yaw_dumbbell","avg_yaw_dumbbell","var_pitch_dumbbell",
                                    "stddev_pitch_dumbbell","avg_pitch_dumbbell","var_roll_dumbbell","stddev_roll_dumbbell",
                                    "avg_roll_dumbbell","var_accel_dumbbell","amplitude_pitch_dumbbell",
                                    "amplitude_roll_dumbbell","min_pitch_dumbbell","max_picth_dumbbell",
                                    "max_roll_dumbbell","amplitude_yaw_arm","min_yaw_arm","max_yaw_arm",
                                    "max_picth_arm","var_accel_arm","var_yaw_belt","avg_yaw_belt","var_pitch_belt",
                                    "stddev_pitch_belt","avg_pitch_belt","var_roll_belt","stddev_roll_belt","avg_roll_belt",
                                    "var_total_accel_belt","amplitude_pitch_belt","amplitude_roll_belt","min_pitch_belt",
                                    "min_roll_belt","max_picth_belt","max_roll_belt",
                                    "min_roll_dumbbell","stddev_yaw_belt")

Train_V3 <- Train_V2[!MissingVal]

modFitA1 <- train(classe ~ ., data=Train_V3, method="rpart")
#  rpart(classe ~ ., data=Train_V3, method="class")

fancyRpartPlot(modFitA1$finalModel)

predA1 <- predict(modFitA1,Test)
confusionMatrix(predA1,Test$classe)

#Using Random Forest

modFitA2 <- train(classe ~ ., data=Train_V3, method="rf", ntree = 1, prox=TRUE)
predA2 <- predict(modFitA2,Test)
confusionMatrix(predA2,Test$classe)


#Accuracy of the model is better in Random Forest Model which is 99%. 

#Selecting this model to use it on our test set

pred_Final <- predict(modFitA2,testing)

pred_Final
```